- name: Update apt packages
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io

- name: Update Max Memory
  shell: sysctl -w vm.max_map_count=262144

- name: Create Docker Network
  shell: docker network create mynetwork --driver=bridge

- name: Start ElasticSearch With Docker
  shell: docker run -d -p 9200:9200 --network mynetwork --name elasticsearch -p 9300:9300 docker.elastic.co/elasticsearch/elasticsearch:6.5.4

- name: Start Kibana With Docker
  shell: docker run -d -p 5601:5601 --network mynetwork --name kibana  docker.elastic.co/kibana/kibana:6.5.4

## - name: Install Necessary Packages
##   apt: 
##     name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
##   
## - name: Add Repo
##   shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
## 
## - name: Add Key
##   command: apt-key fingerprint 0EBFCD88
## 
## - name: Add Repo
##   shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
## 
## - name: Update all packages to the latest version
##   shell: apt-get update
## 
## - name: Install Docker-CE
##   command: apt-get install docker-ce
## 
## - name: Run ElasticSearch
##   docker_container:
##     name: elasticsearch
##     image: elasticsearch:6.5.4
## 
## 