- name: Install MySQL
  apt:
    name: ['python-mysqldb', 'mysql-server']

# Copiar os Ficheiros De Configuração Para as Respectivas Diretorias
- name: Copy MySQL Conf File
  template:
    src: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/ConfigFiles/mysqldM.cnf"
    dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"

- name: Restart MySQL Server
  service:
    name: mysql
    state: restarted

- name: Change Root Password
  mysql_user:
    name: root
    password: 2130
    state: present

- name: Create User For Ghost
  mysql_user:
    login_user: root
    login_password: 2130
    name: ghost_user
    password: 'ghost'
    host: '%'
    priv: '*.*:ALL,GRANT'
    state: present

- name: Create Replication User on Master
  mysql_user:
    login_user: root
    login_password: 2130
    name: replication_user
    password: 'user_replication'
    priv: '*.*:REPLICATION SLAVE,REPLICATION CLIENT'
    host: '%'
    state: present
