- name: Update apt packages
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io

- name: Update Max Memory
  shell: sysctl -w vm.max_map_count=262144

- name: Create Docker Network
  shell: docker network create mynetwork --driver=bridge

- name: Start ElasticSearch With Docker
  shell: docker run -d -p 9200:9200 --network mynetwork --name elasticsearch -p 9300:9300 docker.elastic.co/elasticsearch/elasticsearch:6.5.4

- name: Start Kibana With Docker
  shell: docker run -d -p 5601:5601 --network mynetwork --name kibana docker.elastic.co/kibana/kibana:6.5.4
  