---

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: createInstances
      vars:
        gcp_zone: us-west1-b
        gcp_region: us-west1
        gcp_project: sdb-aula-pratica
        gcp_cred_kind: serviceaccount
        gcp_cred_file: ~/Desktop/UMinho/credentials.json
        gcp_machine_type: f1-micro
        source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
        disk_size: 10
        disks:
          - disk-01
          - disk-02
          # - disk-03
          # - disk-04
          # - disk-05
          # - disk-06
          # - disk-07
          # - disk-08
          # - disk-09
        addresses:
          - addr-01
          - addr-02
          # - addr-03
          # - addr-04
          # - addr-05
          # - addr-06
          # - addr-07
          # - addr-08
          # - addr-09
        instances:
          # - { index: 1, number: 1, tag: monitor }
          # - { index: 2, number: 1, tag: wslb }
          # - { index: 3, number: 1, tag: ws }
          # - { index: 4, number: 2, tag: ws }
          # - { index: 5, number: 1, tag: ghostlb }
          # - { index: 6, number: 1, tag: ghostcore1 }
          # - { index: 7, number: 2, tag: ghostcore2 }
          - { index: 1, number: 1, tag: masterdb }
          - { index: 2, number: 2, tag: slavedb }

# - hosts: monitor
#   become: yes
#   roles: 
#     - role: webLoadBalancers  
# 
# - hosts: wslb
#   become: yes
#   roles: 
#     - role: webLoadBalancers
# 
# - hosts: ws
#   become: yes
#   roles:
#     - role: webServers
# 
# - hosts: ghostlb
#   become: yes
#   roles:
#     - role: ghostLoadBalancers

- hosts: masterdb
  become: yes
  roles:
    - role: masterDB

- hosts: slavedb
  become: yes
  roles:
    - role: slaveDB

# # Concurrency Issues Forced This Solution
# - hosts: ghostcore1
#   become: yes
#   roles:
#     - role: ghostCores
# 
# - hosts: ghostcore2
#   become: yes
#   roles:
#     - role: ghostCores
