- name: Install MySQL
  apt:
    name: ['python-mysqldb', 'mysql-server']

  # Copiar os Ficheiros De Configuração Para as Respectivas Diretorias
- name: Copy MySQL Conf File
  template:
    src: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/ConfigFiles/mysqldS.cnf"
    dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"

- name: Restart MySQL Server
  service:
    name: mysql
    state: restarted

- name: Change Root Password
  mysql_user:
    name: root
    password: 2130
    state: present

- name: Configure replication on the slave.
  mysql_replication:
    mode: changemaster
    login_user: root
    login_password: 2130
    master_host: "10.240.0.2"
    master_user: "replication_user"
    master_password: "user_replication"
    master_log_file: "/var/log/mysql/mysql-bin.000001"
    master_log_pos: "1306"

- name: Start replication.
  mysql_replication: 
    mode: startslave
    login_user: root
    login_password: 2130

############# PRODUCTION ENVIRONMENT  #############

# - name: Enable Metrics For MetricBeat Production
#   shell: ./metricbeat modules enable system mysql
#   args:
#     chdir: ~/metricbeat/
#   become: no
# 
# - name: MetricBeat Initial Setup
#   shell: ./metricbeat setup
#   args:
#     chdir: ~/metricbeat/
#   become: no
# 
# - name: Run MetricBeat
#   shell: nohup ./metricbeat > /dev/null &
#   args:
#     chdir: ~/metricbeat/
#     executable: /bin/bash
#   become: no