# Cria Um Disco Com Boot Para Ubuntu 16.04 LTS
- name: create a disk
  gcp_compute_disk:
      name: "{{ item }}"
      size_gb: 10
      source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
      zone: "{{ gcp_zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
  register: disk
  loop: "{{ disks }}"

# Cria Uma Rede
- name: create a network
  gcp_compute_network:
      name: "sdb-network"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
  register: network

# Cria Um Endereço IP Externo Estático
- name: create a address
  gcp_compute_address:
      name: "{{ item }}"
      region: "{{ gcp_region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
  register: address
  loop: "{{ addresses }}"

# Cria FireWall e Abre a Porta 22 Para Ligações SSH
- name: create a firewall
  gcp_compute_firewall:
    name: "firewall"
    allowed:
      - ip_protocol: tcp
        ports:
          - 22    # ssh
          - 80    # http
          - 443   # https
          - 2368  # Ghost Core
          - 3306  # MySQL 
          - 5601  # Kibana
          - 9200  # ElasticSearch
          - 9300  # ElasticSearch
      - ip_protocol: icmp
    network: "global/networks/{{ network.name }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present

# Cria Uma Instância Com Os Objectos Criados Anteriormente
- name: create an instance
  gcp_compute_instance:
    name: "{{ item.tag }}-{{ '%02d' | format(item.number) }}"
    machine_type: "{{ gcp_machine_type }}"
    metadata:
      startup-script:
        # - apt update -y
    tags:
      items: "{{ item.tag }}"
    disks:
    - auto_delete: true
      boot: true
      source: "{{ disk.results[item.index-1] }}"
    network_interfaces:
    - network: "{{ network }}"
      access_configs:
      - name: External NAT
        nat_ip: "{{ address.results[item.index-1] }}"
        type: ONE_TO_ONE_NAT
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: instance
  loop: "{{ instances }}"

# Replace ElasticSearch IP In MetricBeat Config File
- name: Replace ElasticSearch Internal IP In MetricBeat Config File
  replace:
    path: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/ConfigFiles/metricbeat.yml"
    regexp: 'ELASTICSEARCHIP'
    replace: "{{ instance.results[0].networkInterfaces[0].networkIP }}"

# Replace Kibana IP In MetricBeat Config File
- name: Replace Kibana Internal IP In MetricBeat Config File
  replace:
    path: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/ConfigFiles/metricbeat.yml"
    regexp: 'KIBANAIP'
    replace: "{{ instance.results[0].networkInterfaces[0].networkIP }}"

# Replace 1st WebServer Internal IP in the Web HAProxy Config File
- name: Replace Web HAProxy's 1st IP
  replace:
    path: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/ConfigFiles/webhaproxy.cfg"
    regexp: 'WEBSERVER1'
    replace: "{{ instance.results[2].networkInterfaces[0].networkIP }}"

# Replace 2nd WebServer Internal IP in the Web HAProxy Config File
- name: Replace Web HAProxy's 2nd IP
  replace:
    path: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/ConfigFiles/webhaproxy.cfg"
    regexp: 'WEBSERVER2'
    replace: "{{ instance.results[3].networkInterfaces[0].networkIP }}"

# Replace INTERNALIP Internal IP in NGINX Config File
- name: Replace NGINX Config File
  replace:
    path: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/ConfigFiles/default"
    regexp: 'INTERNALIP'
    replace: "{{ instance.results[4].networkInterfaces[0].networkIP }}"

# Replace 1st GhostCore Internal IP in the Ghost HAProxy Config File
- name: Replace Ghost HAProxy's 1st IP
  replace:
    path: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/ConfigFiles/ghosthaproxy.cfg"
    regexp: 'GHOSTCORE1'
    replace: "{{ instance.results[5].networkInterfaces[0].networkIP }}"

# Replace 2nd GhostCore Internal IP in the Web HAProxy Config File
- name: Replace Ghost HAProxy's 2nd IP
  replace:
    path: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/ConfigFiles/ghosthaproxy.cfg"
    regexp: 'GHOSTCORE2'
    replace: "{{ instance.results[6].networkInterfaces[0].networkIP }}"

# Replace URL In Ghost Config File
- name: Replace Ghost URL In Ghost Config File
  replace:
    path: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/ConfigFiles/config.production.json"
    regexp: 'EXTERNALURL'
    replace: "{{ instance.results[1].networkInterfaces[0].accessConfigs[0].natIP }}"

# Replace MySQL IP In Ghost Config File
- name: Replace MySQL Internal IP In Ghost Config File
  replace:
    path: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/ConfigFiles/config.production.json"
    regexp: 'MySQLINTERNALIP'
    replace: "{{ instance.results[7].networkInterfaces[0].networkIP }}"

- name: Add hosts to in memory inventory
  add_host:
    name: "{{ item.networkInterfaces[0].accessConfigs[0].natIP }}"
    groups: "{{ item.tags['items'] | join(',') }}"
  loop: "{{ instance.results }}"

- name: Wait for instances to respond
  wait_for:
    host: "{{ item }}"
    port: 22
  loop: "{{ groups['all'] }}"
  