- name: Add Nodejs 8 Repository
  shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  become: yes

- name: Install Nodejs 8
  command: apt-get install -y nodejs warn=False
  become: yes
  

- name: Install Ghost-CLI
  command: npm install ghost-cli@latest -g
  become: yes

# Create Ghost Installation Directory if t Doesn't Exist
- name: Create Ghost Installation Directory
  file:
    path: ~/gh/
    state: directory

- name: Install Ghost Inside ~/gh/
  command: ghost install local
  args:
    chdir: ~/gh/

- name: Stop Local Ghost Installation
  command: ghost stop
  args:
    chdir: ~/gh/

- name: Remove Ghost Configuration File
  file:
    path: ~/gh/config.development.json
    state: absent
    
# Copiar o Ficheiro De Configuração Para a Respectiva Diretoria
- name: Copy Ghost Configuration File
  template:
    src: "~/Desktop/UMinho/4º\ Ano/1º\ Semestre/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/ConfigFiles/config.production.json"
    dest: "~/gh/config.production.json"

- name: Start Ghost With New Config File
  command: ghost start
  args:
    chdir: ~/gh/

############# PRODUCTION ENVIRONMENT  #############

# - name: Enable Metrics For MetricBeat Production
#   shell: ./metricbeat modules enable system
#   args:
#     chdir: ~/metricbeat/
#   become: no
# 
# - name: MetricBeat Initial Setup
#   shell: ./metricbeat setup
#   args:
#     chdir: ~/metricbeat/
#   become: no
# 
# - name: Run MetricBeat
#   shell: nohup ./metricbeat > /dev/null &
#   args:
#     chdir: ~/metricbeat/
#     executable: /bin/bash
#   become: no