- name: Install Keepalived
  apt:
    name: keepalived
  tags:
    - wslb

- name: Install HAProxy
  apt:
    name: haproxy
  tags:
    - wslb

# Copiar os Ficheiros De Configuração Para as Respectivas Diretorias
- name: Copy HAProxy Configuration File
  template:
    src: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/haproxy.cfg"
    dest: "/etc/haproxy/haproxy.cfg"
  tags:
    - wslb

- name: Copy KeepAlived Configuration File
  template:
    src: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/keepalived.conf"
    dest: "/etc/keepalived/keepalived.conf"
  tags:
    - wslb
 
- name: restart haproxy
  service:
    name: haproxy
    state: restarted

- name: restart keepalived
  service:
    name: keepalived
    state: restarted