- name: Install nginx
  apt:
    name: nginx
  tags:
    - ws

# Copiar os Ficheiros De Configuração Para as Respectivas Diretorias
- name: Copy NGINX Configuration File
  template:
    src: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/ConfigFiles/default"
    dest: "/etc/nginx/sites-available/default"
  tags:
    - ws

# Copiar os Ficheiros De Configuração Para as Respectivas Diretorias
- name: Copy NGinX Configuration File
  template:
    src: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/ConfigFiles/default"
    dest: "/etc/nginx/sites-enabled/default"
  tags:
    - ws

- name: Restart nginx
  service:
    name: nginx
    state: restarted

############# PRODUCTION ENVIRONMENT  #############

# - name: Enable Metrics For MetricBeat Production
#   shell: ./metricbeat modules enable system nginx
#   args:
#     chdir: ~/metricbeat/
#   become: no
# 
# - name: MetricBeat Initial Setup
#   shell: ./metricbeat setup
#   args:
#     chdir: ~/metricbeat/
#   become: no
# 
# - name: Run MetricBeat
#   shell: nohup ./metricbeat > /dev/null &
#   args:
#     chdir: ~/metricbeat/
#     executable: /bin/bash
#   become: no