- name: Install HAProxy
  apt:
    name: haproxy
  tags:
    - wslb

# Copiar os Ficheiros De Configuração Para as Respectivas Diretorias
- name: Copy HAProxy Configuration File
  template:
    src: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/ConfigFiles/webhaproxy.cfg"
    dest: "/etc/haproxy/haproxy.cfg"
  tags:
    - wslb

- name: restart haproxy
  service:
    name: haproxy
    state: restarted