- name: Install HAProxy
  apt:
    name: haproxy

# Copiar os Ficheiros De Configuração Para as Respectivas Diretorias
- name: Copy HAProxy Configuration File
  template:
    src: "~/Desktop/UMinho/4º\ Ano/Comp\ SD\ -\ System\ Deployment\ and\ Benchmarking/SDB2018-TP/Fase2/Ghost/ConfigFiles/webhaproxy.cfg"
    dest: "/etc/haproxy/haproxy.cfg"

- name: restart haproxy
  service:
    name: haproxy
    state: restarted

############# PRODUCTION ENVIRONMENT  #############

# - name: Enable Metrics For MetricBeat Production
#   shell: ./metricbeat modules enable system haproxy
#   args:
#     chdir: ~/metricbeat/
#   become: no
# 
# - name: MetricBeat Initial Setup
#   shell: ./metricbeat setup
#   args:
#     chdir: ~/metricbeat/
#   become: no
# 
# - name: Run MetricBeat
#   shell: nohup ./metricbeat > /dev/null &
#   args:
#     chdir: ~/metricbeat/
#     executable: /bin/bash
#   become: no